---

- name: Setup bonding
  block:
    - name: Create config files for bond slave interfaces
      ansible.builtin.template:
        src: bond_slave.j2
        dest: >-
          {{ network_devices_scripts_dir }}/ifcfg-{{ interface.logicalname }}
        mode: 0755
      loop: >-
        {{ network_interfaces
           | selectattr("bond_master", "defined")
           | list }}
      loop_control:
        loop_var: interface
        label: "{{ interface.logicalname }}"
      notify:
        - reboot host
        - wait host

    - name: Create config files for bond master interfaces
      ansible.builtin.template:
        src: bond_master.j2
        dest: >-
          {{ network_devices_scripts_dir }}/ifcfg-{{ interface.logicalname }}
        mode: 0755
      loop: >-
        {{ network_interfaces
           | selectattr("bond_options", "defined")
           | selectattr("bond_master", "undefined")
           | list }}
      loop_control:
        loop_var: interface
        label: "{{ interface.logicalname }}"
      notify:
        - reboot host
        - wait host

    - name: Create configuration file for bonding module
      ansible.builtin.template:
        src: bond_config.j2
        dest: "{{ network_devices_bonding_config_path }}"
        mode: 0755
      loop: >-
        {{ network_interfaces
           | selectattr("bond_options", "defined")
           | selectattr("bond_master", "undefined")
           | list }}
      loop_control:
        loop_var: interface
        label: "{{ interface.logicalname }}"
  tags:
    - role::network_interfaces
    - role::network_interfaces::bonding