---
# Role check tasks

- block:
    - name: assert platform is supported
      assert:
        that:
          - distribution in network_interfaces_supported_distributions
          - >-
            ansible_facts.distribution_version
            is version(network_interfaces_supported_versions[distribution], ">=")
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::network_interfaces
    - role::network_interfaces::check
