---
# Cleanup

- block:
    - block:
        - name: Gather service facts
          service_facts:

        - name: Disable NetworkManager service
          service:
            name: NetworkManager
            enabled: no
            state: stopped
          when: >-
            'NetworkManager.service' in ansible_facts.services.keys() | list

        - name: Remove NetworkManager package
          package:
            name: NetworkManager
            state: absent
      when: ansible_facts.distribution_major_version is version("7", ">=")

    - name: Remove unnecessary config files
      file:
        path: "{{ network_interfaces_config_file }}"
        state: absent
      loop: >-
        {{ lookup('template', 'files_to_clean.yml.j2') | from_yaml | unique }}
      loop_control:
        loop_var: network_interfaces_config_file
      notify:
        - reboot host
        - wait host
  tags:
    - role::network_interfaces
    - role::network_interfaces::cleanup
