---
# Cleanup

- block:
    - block:
        - name: gather service facts
          service_facts:

        - name: disable NetworkManager service
          service:
            name: NetworkManager
            enabled: no
            state: stopped
          when: >-
            'NetworkManager.service' in ansible_facts.services.keys()

        - name: remove NetworkManager package
          package:
            name: NetworkManager
            state: absent
      when: ansible_facts.distribution_major_version is version("7", ">=")

    - name: remove old interface config files
      file:
        path: "{{ network_interfaces_config_file }}"
        state: absent
      loop: "{{ lookup('template', 'files_to_clean.yml.j2') | from_yaml }}"
      loop_control:
        loop_var: network_interfaces_config_file
      notify:
        - reboot host
        - wait host
  tags:
    - role::network_interfaces
    - role::network_interfaces::cleanup
