---

- name: Create a ifcfg config file for every interface without vlanid
  template:
    src: ifcfg_template.j2
    dest: "{{ network_scripts_path }}/ifcfg-{{ device.logicalname }}"
  with_items: "{{ nics }}"
  when: device.vlanid is undefined
  loop_control:
    loop_var: device

- name: Create a ifcfg config file for every base device for vlan tagged interfaces
  template:
    src: ifcfg_vlan_base_template.j2
    dest: "{{ network_scripts_path }}/ifcfg-{{ item.logicalname }}"
  with_items: "{{ nics }}"
  when: item.vlanid is defined

- name: Create a ifcfg config file for every interface vith vlanid
  template:
    src: ifcfg_vlan_template.j2
    dest: "{{ network_scripts_path }}/ifcfg-{{ device.logicalname }}.{{ device.vlanid }}"
  with_items: "{{ nics }}"
  when: device.vlanid is defined
  loop_control:
    loop_var: device
