---
- block:
    - name: create a ifcfg config file for every interface without vlanid
      template:
        src: ifcfg_template.j2
        dest: "{{ network_scripts_path }}/ifcfg-{{ device.logicalname }}"
      with_items: "{{ nics }}"
      when:
        - device.vlanid is undefined
        - item.bond is not defined
      loop_control:
        loop_var: device
      notify:
        - reboot host
        - wait host

    - name: create a ifcfg config file for every base device for vlan tagged interfaces
      template:
        src: ifcfg_vlan_base_template.j2
        dest: "{{ network_scripts_path }}/ifcfg-{{ item.logicalname }}"
      with_items: "{{ nics }}"
      when:
        - item.vlanid is defined
        - item.bond is not defined
      notify:
        - reboot host
        - wait host

    - name: create a ifcfg config file for every interface vith vlanid
      template:
        src: ifcfg_vlan_template.j2
        dest: "{{ network_scripts_path }}/ifcfg-{{ device.logicalname }}.{{ device.vlanid }}"
      with_items: "{{ nics }}"
      when:
        - device.vlanid is defined
        - item.bond is not defined
      loop_control:
        loop_var: device
      notify:
        - reboot host
        - wait host
  tags:
    - role::network_interfaces
    - role::network_interfaces::ifcfg
