---
- block:
    - name: create a route config file per device if is needed
      template:
        src: route.j2
        dest: "{{ network_scripts_path }}/route-{{ device.logicalname }}"
      with_items: "{{ nics }}"
      when: device.route is defined
      loop_control:
        loop_var: device
      notify:
        - reboot host
        - wait host

    - name: create a route config file for multicast per device if is needed
      template:
        src: route_multicast.j2
        dest: "{{ network_scripts_path }}/route-{{ item.logicalname }}"
      with_items: "{{ nics }}"
      when: item.route_multicast is defined
      notify:
        - reboot host
        - wait host
              
  tags:
    - role::network_interfaces
    - role::network_interfaces::config_routes
