

- name: Create a ifcfg config file for every slave interface for bond
  template:
    src: bond_slave.j2
    dest: "{{ network_scripts_path }}/ifcfg-{{ item.logicalname }}"
  with_items: "{{ nics }}"
  when:
    - item.bond is defined
    - item.bondmaster is defined

- name: Create a ifcfg config file for every interface vith bond defined
  template:
    src: bond_master.j2
    dest: "{{ network_scripts_path }}/ifcfg-{{ device.logicalname }}"
  with_items: "{{ nics }}"
  when:
    - device.bond is defined
    - device.bondmaster is not defined
  loop_control:
    loop_var: device

- name: Create configuration file for bonding module
  template:
    src: bond_config.j2
    dest: "{{ mod_bonding_configuration_file }}"
  with_items: "{{ nics }}"
  when:
    - item.bond is defined
    - item.bondmaster is not defined
