---
- name: Remove NetworkManager package
  package:
    name: NetworkManager
    state: absent
  when: ansible_distribution_version | version_compare('7', '>=')
  notify: Deactivate biosdevname for CentOS / RHEL 7

- name: Enabled network service
  service:
    name: network
    enabled: yes
    state: started
