---
# Disable IPv6 tasks

- block:
    - name: disable ipv6 in sysctl
      sysctl:
        name: "{{ network_interfaces_sysctl_item }}"
        value: 1
        state: present
        reload: yes
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
      loop_control:
        loop_var: network_interfaces_sysctl_item

    - name: remove ipv6 localhost address from /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^\:\:1'
        state: absent

    - name: prevent udp rpcbind for ipv6
      replace:
        path: /etc/netconfig
        regexp: '^udp6'
        replace: '#udp6'
      when: ansible_facts.distribution_major_version is version("6", "==")

    - name: prevent tcp rpcbind for ipv6
      replace:
        path: /etc/netconfig
        regexp: '^tcp6'
        replace: '#tcp6'
      when: ansible_facts.distribution_major_version is version("6", "==")
  when: not network_interfaces_ipv6
  tags:
    - role::network_interfaces
    - role::network_interfaces::ipv6
