---
- name: Disable NetworkManager service
  service:
    name: NetworkManager
    enabled: no
    state: stopped
  when: ansible_distribution_version | version_compare('7', '>=')


- name: Enabled network service
  service:
    name: network
    enabled: yes
    state: started

- name: Remove NetworkManager package
  package:
    name: NetworkManager
    state: absent
  when: ansible_distribution_version | version_compare('7', '>=')
