---
# DNS config tasks

- name: Setup dns config
  template:
    src: resolv.conf.j2
    dest: "{{ network_devices_resolv_config_path }}"
  tags:
    - role::network_interfaces
    - role::network_interfaces::dns
