---
- name: Install 802.1q kernel module
  shell: modprobe -i 8021q

- name: Install bonding kernel module
  shell: modprobe -i bonding

- name: Disable ipv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- name: Remove ipv6 localhost from /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^\:\:1'
    state: absent

- name: Prevent udp rpcbind for ipv6
  replace:
    dest: /etc/netconfig
    regexp: '^udp6'
    replace: '#udp6'

- name: Prevent tcp rpcbind for ipv6
  replace:
    dest: /etc/netconfig
    regexp: '^tcp6'
    replace: '#tcp6'

- name: Reload sysctl with ipv6 disabled
  shell: sysctl -p

- name: Remove old icfg-interface config config files
  file:
    path: "{{ network_scripts_path }}/ifcfg-{{ item }}"
    state: absent
  with_items: "{{ ansible_interfaces| difference(['lo']) }}"

- name: Create dns configuration file
  template:
    src: dns_config_template.j2
    dest: "{{ dns_config_file_path }}"

- name: Create a general network parameters file
  template:
    src: sysconfig_network_template.j2
    dest: "{{ sysconfig_network_file_path }}"
