---
- name: Install 802.1q kernel module
  shell: modprobe -i 8021q

- name: Remove old icfg-interface config config files
  file:
    path: "{{ network_scripts_path }}/ifcg-{{ item }}"
    state: absent
  with_items: "{{ ansible_interfaces| difference(['lo']) }}"
  
- name: Create dns configuration file
  template:
    src: dns_config_template.j2
    dest: "{{ dns_config_file_path }}"

- name: Create a general network parameters file
  template:
    src: sysconfig_network_template.j2
    dest: "{{ sysconfig_network_file_path }}"
