---
- block:
    - name: create array with a list of prefetch mac address by ip address
      set_fact:
        extract_mac_by_ip: >-
          {{ lookup('template', 'prefetch_mac_list.j2') | from_yaml }}
    - name: install 802.1q kernel module
      modprobe:
        name: 8021q
        state: present

    - name: disable ipv6
      sysctl:
        name: "{{ item }}"
        value: 1
        state: present
        reload: yes
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6

    - name: remove ipv6 localhost from /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^\:\:1'
        state: absent

    - name: prevent udp rpcbind for ipv6
      replace:
        path: /etc/netconfig
        regexp: '^udp6'
        replace: '#udp6'
      when: ansible_facts.distribution_major_version == "6"

    - name: prevent tcp rpcbind for ipv6
      replace:
        path: /etc/netconfig
        regexp: '^tcp6'
        replace: '#tcp6'
      when: ansible_facts.distribution_major_version == "6"

    - name: incorpore vlan interfaces to definitive interfaces list
      set_fact:
        definitive_interfaces: "{{ definitive_interfaces + [ item.logicalname ~ '.' ~ item.vlanid ] }}"
      with_items: "{{ nics }}"
      when: item.vlanid is defined

    - name: remove old icfg-interface config config files
      file:
        path: "{{ network_scripts_path }}/ifcfg-{{ item }}"
        state: absent
      with_items: "{{ ansible_facts.interfaces| difference(definitive_interfaces) }}"
      when: ansible_facts.interfaces|difference(definitive_interfaces)|length > 0

    - name: create dns configuration file
      template:
        src: dns_config_template.j2
        dest: "{{ dns_config_file_path }}"

    - name: create a general network parameters file
      template:
        src: sysconfig_network_template.j2
        dest: "{{ sysconfig_network_file_path }}"

    - name: enabled network service
      service:
        name: network
        enabled: yes
        state: started
  tags:
    - role::network_interfaces
    - role::network_interfaces:config
