---
#  Configure required kernel modules

- block:
    - name: configure 802.1q module
      copy:
        dest: /etc/modules-load.d/8021q.conf
        content: 8021q
      when: nics | selectatrr("vlanid", "defined") | list > 0

    - name: configure bonding module
      copy:
        dest: /etc/modules-load.d/bonding.conf
        content: bonding
      when: nics | selectatrr("bond", "defined") | list > 0
  tags:
    - role::network_interfaces
    - role::network_interfaces::kernel_modules
