---

- name: Setup kernel modules
  block:
    - name: Configure 802.1q module
      ansible.builtin.copy:
        dest: /etc/modules-load.d/8021q.conf
        content: 8021q
        mode: 0644
      when: >-
        network_interfaces
        | selectattr("vlanid", "defined")
        | list
        | length > 0

    - name: Configure bonding module
      ansible.builtin.copy:
        dest: /etc/modules-load.d/bonding.conf
        content: bonding
        mode: 0644
      when: >-
        network_interfaces
        | selectattr("bond_master", "defined")
        | list
        | length > 0
  tags:
    - role::network_interfaces
    - role::network_interfaces::kernel_modules