---
# Role tasks
- block:
    - import_tasks: manage_packages.yml
    - import_tasks: general_network_config.yml

    - include_tasks: kernel_modules.yml

    - import_tasks: config_udev.yml
    - import_tasks: config_ifcfg_files.yml
    - import_tasks: config_route_files.yml
    - import_tasks: restart_net.yml


  tags:
    - role::network_interfaces
