---

- name: Setup network interfaces
  block:
    - ansible.builtin.include_tasks: prerequisites.yml

    - ansible.builtin.include_tasks: facts.yml
      tags:
        - role::network_interfaces::facts

    - ansible.builtin.include_tasks: cleanup.yml
      tags:
        - role::network_interfaces::cleanup

    - ansible.builtin.include_tasks: disable_ipv6.yml

      tags:
        - role::network_interfaces::ipv6

    - ansible.builtin.include_tasks: sysconfig.yml
      tags:
        - role::network_interfaces::sysconfig

    - ansible.builtin.include_tasks: hostname.yml
      tags:
        - role::network_interfaces::hostname

    - ansible.builtin.include_tasks: dns.yml
      tags:
        - role::network_interfaces::dns

    - ansible.builtin.include_tasks: kernel_modules.yml
      tags:
        - role::network_interfaces::kernel_modules

    - ansible.builtin.include_tasks: udev.yml
      tags:
        - role::network_interfaces::udev

    - ansible.builtin.include_tasks: ifcfg.yml
      tags:
        - role::network_interfaces::ifcfg

    - ansible.builtin.include_tasks: bonding.yml
      tags:
        - role::network_interfaces::bonding

    - ansible.builtin.include_tasks: routes.yml
      tags:
        - role::network_interfaces::routes

    - ansible.builtin.include_tasks: service.yml
      tags:
        - role::network_interfaces::service

    - ansible.builtin.include_tasks: clean_arp.yml
      tags:
        - role::network_interfaces::service
  tags:
    - role::network_interfaces
