---
# Role tasks

- block:
    - include_tasks: facts.yml
    - include_tasks: cleanup.yml
    - include_tasks: disable_ipv6.yml
    - include_tasks: sysconfig.yml
    - include_tasks: hostname.yml
    - include_tasks: dns.yml
    - include_tasks: kernel.yml
    - include_tasks: udev.yml
    - include_tasks: ifcfg.yml
    - include_tasks: bonding.yml
    - include_tasks: routes.yml
    - include_tasks: service.yml
    - include_tasks: reboot.yml
  tags:
    - role::network_interfaces
