---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6

- include_role:
    name: amtega.grub_options
  vars:
    grub_options_present:
      - "net.ifnames=0"
      - "biosdevname=0"
  when: ansible_facts.distribution_version is version_compare("7", ">=")

- include_role:
    name: amtega.sysctl
  vars:
    sysctl:
      - name: disable_ipv6
        options:
          - name: net.ipv6.conf.all.disable_ipv6
            value: 1
            reload: yes
            sysctl_set: yes
            state: present
          - name: net.ipv6.conf.default.disable_ipv6
            value: 1
            reload: yes
            sysctl_set: yes
            state: present

- include_role:
    name: amtega.reboot

- block:
    - include_tasks: facts.yml
      tags:
        - role::network_interfaces::facts

    - include_tasks: cleanup.yml
      tags:
        - role::network_interfaces::cleanup

    - include_tasks: disable_ipv6.yml

      tags:
        - role::network_interfaces::ipv6

    - include_tasks: sysconfig.yml
      tags:
        - role::network_interfaces::sysconfig

    - include_tasks: hostname.yml
      tags:
        - role::network_interfaces::hostname

    - include_tasks: dns.yml
      tags:
        - role::network_interfaces::dns

    - include_tasks: kernel_modules.yml
      tags:
        - role::network_interfaces::kernel_modules

    - include_tasks: udev.yml
      tags:
        - role::network_interfaces::udev

    - include_tasks: ifcfg.yml
      tags:
        - role::network_interfaces::ifcfg

    - include_tasks: bonding.yml
      tags:
        - role::network_interfaces::bonding

    - include_tasks: routes.yml
      tags:
        - role::network_interfaces::routes

    - include_tasks: service.yml
      tags:
        - role::network_interfaces::service
  tags:
    - role::network_interfaces
