---
# Service config tasks

- name: enable network service
  service:
    name: network
    enabled: yes
    state: started
  tags:
    - role::network_interfaces
    - role::network_interfaces::service
