---
# Sysconfig network tasks

- name: Setup main sysconfig network options
  template:
    src: sysconfig_network.j2
    dest: "{{ network_devices_network_config_path }}"
  tags:
    - role::network_interfaces
    - role::network_interfaces::sysconfig
