---
# UDEV config tasks

- name: create udev persistent net rules
  template:
    src: persistent_net_rules.j2
    dest: "{{ network_devices_udev_persistent_rules_path }}"
  notify:
    - reboot host
    - wait host
  tags:
    - role::network_interfaces
    - role::network_interfaces::udev
